default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: db
  username: postgres
  password: password

test:
  <<: *default
  host: db
  username: postgres
  password: password

production:
  url: <%= ENV["DATABASE_URL"] %>
