default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: gameadd_development

test:
  <<: *default
  database: gameadd_test

production:
  <<: *default
  database: gameadd_production
